export const TESTING_ACTION_TYPE = 'TESTING_ACTION_TYPE';

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const SUBMIT_USER_PENDING = 'SUBMIT_USER_PENDING';
export const SUBMIT_USER_FULFILLED = 'SUBMIT_USER_FULFILLED';
export const SUBMIT_USER_REJECTED = 'SUBMIT_USER_REJECTED';

export const GET_ALL_BOOKS_PENDING = 'GET_ALL_BOOKS_PENDING';
export const GET_ALL_BOOKS_FULFILLED = 'GET_ALL_BOOKS_FULFILLED';
export const GET_ALL_BOOKS_REJECTED = 'GET_ALL_BOOKS_REJECTED';

export const VALIDATE_TOKEN_PENDING = 'VALIDATE_TOKEN_PENDING';
export const VALIDATE_TOKEN_FULFILLED = 'VALIDATE_TOKEN_FULFILLED';
export const VALIDATE_TOKEN_REJECTED = 'VALIDATE_TOKEN_REJECTED';

export const LOGOUT_USER_FULFILLED = 'LOGOUT_USER_FULFILLED';

export const CREATE_BOOK_PENDING = 'CREATE_BOOK_PENDING';
export const CREATE_BOOK_FULFILLED = 'CREATE_BOOK_FULFILLED';
export const CREATE_BOOK_REJECTED = 'CREATE_BOOK_REJECTED';

export const UPDATE_BOOK_PENDING = 'UPDATE_BOOK_PENDING';
export const UPDATE_BOOK_FULFILLED = 'UPDATE_BOOK_FULFILLED';
export const UPDATE_BOOK_REJECTED = 'UPDATE_BOOK_REJECTED';

export const DELETE_BOOK_PENDING = 'DELETE_BOOK_PENDING';
export const DELETE_BOOK_FULFILLED = 'DELETE_BOOK_FULFILLED';
export const DELETE_BOOK_REJECTED = 'DELETE_BOOK_REJECTED';